name: .NET Core Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sports-reservation-webapi:latest
      
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |   
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sports-reservation-webapi:latest
            
            sudo docker stop sports-reservation-webapi
            sudo docker sports-reservation-webapi
            
            sudo docker run -d --name sports-reservation-webapi -p 80:8080 ${{ secrets.DOCKER_USERNAME }}/sports-reservation-webapi:latest
            